name: api-bench-gitea-action Hadolint
on:
  push:
    branches:
      - the-one
    paths:
      - 'containers/api-bench-gitea-action/Dockerfile'
      - '.github/workflows/api-bench-gitea-action.hadolint.yml'
  pull_request:
    branches:
      - the-one
    paths:
      - 'containers/api-bench-gitea-action/Dockerfile'
      - '.github/workflows/api-bench-gitea-action.hadolint.yml'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-gitea-action/Dockerfile
